[server]
headless = true
maxUploadSize = 4096   # 4 GB, pick what you need


[theme]
base = "light"
primaryColor = "#F63366"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
